import type { TaskType } from "../types.js";
import { getCatalogueEntry } from "./catalogue.js";
import { aggregateObserved } from "./observed.js";
import { loadProfile } from "./profiler.js";
import type {
  CatalogueModelEntry,
  ModelProfile,
  ModelScore,
  ObservedPerformance,
  ScorerWeights,
} from "./types.js";

const DEFAULT_WEIGHTS: ScorerWeights = {
  quality: 0.5,
  cost: 0.3,
  speed: 0.15,
  contextFit: 0.05,
};

/**
 * Minimum observed routing events before observed data influences blending.
 * Below this threshold the sample is too small to be statistically meaningful,
 * so we rely on catalogue/profile data instead.
 */
const MIN_OBSERVED_THRESHOLD = 50;

/**
 * Normalisation ceilings for mapping raw cost/latency values to 0–1 scores.
 * - MAX_COST_PER_MTOK: $80/MTok output covers the most expensive current models
 *   (e.g. Claude Opus 4.6 at $75/MTok). Models at or above this pay the full cost penalty.
 * - MAX_TTFT_MS: 5 000 ms covers slow reasoning models (o3 at ~3 000 ms).
 *   Anything slower is treated as maximally slow.
 */
const MAX_COST_PER_MTOK = 80;
const MAX_TTFT_MS = 5000;

/**
 * Score a single model for a given task type by blending three data layers:
 *
 * 1. Community catalogue (shipped benchmarks)
 * 2. Local model profile (generated by `openclaw routing profile`)
 * 3. Observed performance (accumulated routing events)
 *
 * Blending formula (adaptive):
 * - New model, no profile:       100% catalogue
 * - Profiled, few observations:  50% catalogue + 50% profile
 * - Established (50+ observed):  20% catalogue + 20% profile + 60% observed
 */
export async function scoreModel(params: {
  model: string;
  taskType: TaskType;
  weights?: Partial<ScorerWeights>;
  stateDir?: string;
  contextNeeded?: number;
}): Promise<ModelScore> {
  const { model, taskType, stateDir } = params;
  const weights = { ...DEFAULT_WEIGHTS, ...params.weights };

  const catalogueEntry = getCatalogueEntry(model);
  const profile = await loadProfile(model, stateDir);
  const observed = await aggregateObserved(model, taskType, stateDir);

  return computeScore({
    model,
    taskType,
    catalogueEntry,
    profile,
    observed,
    weights,
    contextNeeded: params.contextNeeded,
  });
}

/**
 * Synchronous scoring when all data is already available.
 * Useful for batch scoring without repeated I/O.
 */
export function scoreModelSync(params: {
  model: string;
  taskType: TaskType;
  catalogueEntry?: CatalogueModelEntry;
  profile?: ModelProfile;
  observed?: ObservedPerformance;
  weights?: Partial<ScorerWeights>;
  contextNeeded?: number;
}): ModelScore {
  const weights = { ...DEFAULT_WEIGHTS, ...params.weights };
  return computeScore({
    model: params.model,
    taskType: params.taskType,
    catalogueEntry: params.catalogueEntry,
    profile: params.profile,
    observed: params.observed,
    weights,
    contextNeeded: params.contextNeeded,
  });
}

function computeScore(params: {
  model: string;
  taskType: TaskType;
  catalogueEntry?: CatalogueModelEntry;
  profile?: ModelProfile;
  observed?: ObservedPerformance;
  weights: ScorerWeights;
  contextNeeded?: number;
}): ModelScore {
  const { model, taskType, catalogueEntry, profile, observed, weights, contextNeeded } = params;

  // --- Layer scores ---
  const catalogueScore = catalogueEntry?.taskScores[taskType] ?? 0;
  const profileScore = profile?.taskScores[taskType] ?? 0;
  const observedScore = observed?.effectiveScore ?? 0;

  const hasCatalogue = catalogueEntry !== undefined;
  const hasProfile = profile !== undefined;
  const hasObserved = observed !== undefined && observed.requests >= MIN_OBSERVED_THRESHOLD;

  // --- Adaptive blending ---
  let qualityScore: number;
  let source: ModelScore["source"];

  if (hasObserved && hasProfile && hasCatalogue) {
    qualityScore = 0.2 * catalogueScore + 0.2 * profileScore + 0.6 * observedScore;
    source = "blended";
  } else if (hasObserved && hasCatalogue) {
    qualityScore = 0.3 * catalogueScore + 0.7 * observedScore;
    source = "blended";
  } else if (hasProfile && hasCatalogue) {
    qualityScore = 0.5 * catalogueScore + 0.5 * profileScore;
    source = "blended";
  } else if (hasObserved) {
    qualityScore = observedScore;
    source = "observed";
  } else if (hasProfile) {
    qualityScore = profileScore;
    source = "profile";
  } else if (hasCatalogue) {
    qualityScore = catalogueScore;
    source = "catalogue";
  } else {
    // Unknown model — default to mid-tier score
    qualityScore = 0.5;
    source = "catalogue";
  }

  // --- Cost score (lower cost = higher score) ---
  const costPerMTok = catalogueEntry?.cost.outputPerMTok ?? 10;
  const costScore = 1 - Math.min(costPerMTok / MAX_COST_PER_MTOK, 1);

  // --- Speed score (lower latency = higher score) ---
  const ttft = profile?.latency.ttft_ms ?? catalogueEntry?.latency.ttft_ms ?? 1000;
  const speedScore = 1 - Math.min(ttft / MAX_TTFT_MS, 1);

  // --- Context fit (does the model's window cover the need?) ---
  let contextFit = 1.0;
  if (contextNeeded !== undefined && catalogueEntry) {
    contextFit =
      catalogueEntry.contextWindow >= contextNeeded
        ? 1.0
        : catalogueEntry.contextWindow / contextNeeded;
  }

  // --- Composite score ---
  const composite =
    weights.quality * qualityScore +
    weights.cost * costScore +
    weights.speed * speedScore +
    weights.contextFit * contextFit;

  return {
    model,
    composite,
    qualityScore,
    costScore,
    speedScore,
    contextFit,
    source,
  };
}

/**
 * Score all available models for a task type and return them sorted best-first.
 */
export async function selectBestModel(params: {
  taskType: TaskType;
  availableModels: string[];
  weights?: Partial<ScorerWeights>;
  stateDir?: string;
  contextNeeded?: number;
}): Promise<ModelScore[]> {
  const { taskType, availableModels, weights, stateDir, contextNeeded } = params;

  const scores = await Promise.all(
    availableModels.map((model) =>
      scoreModel({ model, taskType, weights, stateDir, contextNeeded }),
    ),
  );

  return scores.toSorted((a, b) => b.composite - a.composite);
}
