import type { TaskType } from "../types.js";

// ---------------------------------------------------------------------------
// Community catalogue (shipped JSON)
// ---------------------------------------------------------------------------

/** Per-model per-task score from community benchmarks. */
export type CatalogueModelEntry = {
  displayName: string;
  suggestedTier: "cheap" | "mid" | "frontier";
  /** Normalised 0–1 scores per task type. */
  taskScores: Partial<Record<TaskType, number>>;
  cost: {
    inputPerMTok: number;
    outputPerMTok: number;
    cacheReadPerMTok?: number;
  };
  latency: {
    /** Time to first token in ms. */
    ttft_ms: number;
    /** Tokens per second. */
    tps: number;
  };
  contextWindow: number;
  toolSupport: boolean;
  reasoning: boolean;
};

/** Top-level shape of the shipped benchmark-catalogue.json. */
export type BenchmarkCatalogue = {
  catalogueVersion: string;
  lastUpdated: string;
  models: Record<string, CatalogueModelEntry>;
};

// ---------------------------------------------------------------------------
// Local model profiles (generated by `openclaw routing profile`)
// ---------------------------------------------------------------------------

/** Profile generated by running benchmark prompts against a local model. */
export type ModelProfile = {
  model: string;
  profiledAt: string;
  taskScores: Partial<Record<TaskType, number>>;
  latency: {
    ttft_ms: number;
    tps: number;
  };
};

// ---------------------------------------------------------------------------
// Observed performance (accumulated JSONL)
// ---------------------------------------------------------------------------

/** Single routing event appended to the observed log. */
export type RoutingEvent = {
  timestamp: string;
  model: string;
  taskType: TaskType;
  success: boolean;
  retried: boolean;
  escalated: boolean;
  latencyMs: number;
  inputTokens: number;
  outputTokens: number;
};

/** Aggregated observed performance for a model+task pair. */
export type ObservedPerformance = {
  model: string;
  taskType: TaskType;
  period: string;
  requests: number;
  successRate: number;
  retryRate: number;
  escalationRate: number;
  avgLatencyMs: number;
  avgInputTokens: number;
  avgOutputTokens: number;
  userOverrideRate: number;
  effectiveScore: number;
};

// ---------------------------------------------------------------------------
// Composite scorer output
// ---------------------------------------------------------------------------

/** Composite score output from the scorer for a single model. */
export type ModelScore = {
  model: string;
  composite: number;
  qualityScore: number;
  costScore: number;
  speedScore: number;
  contextFit: number;
  source: "catalogue" | "profile" | "observed" | "blended";
};

/** Weight configuration for composite scoring. */
export type ScorerWeights = {
  quality: number;
  cost: number;
  speed: number;
  contextFit: number;
};

/** Scorer configuration attached to routing config. */
export type ScorerConfig = {
  weights?: Partial<ScorerWeights>;
};
